export const list = [
  {
    img: "https://picsum.photos/200",
    name: "Holbrook, Arizona, US",
    location: "Calaca, Calabarzon, Philippines",
    date: "May 4 - 5",
    rating: "4.8 (230)",
    price: "95",
    time: "night",
    like: true,
  },
  {
    img: "https://picsum.photos/200",
    name: "Holbrook, Arizona, US",
    location: "Calaca, Calabarzon, Philippines",
    date: "May 4 - 5",
    rating: "4.8 (230)",
    price: "95",
    time: "night",
    like: true,
  },
  {
    img: "https://picsum.photos/200",
    name: "Holbrook, Arizona, US",
    location: "Calaca, Calabarzon, Philippines",
    date: "May 4 - 5",
    rating: "4.8 (230)",
    price: "95",
    time: "night",
    like: true,
  },
  {
    img: "https://picsum.photos/200",
    name: "Holbrook, Arizona, US",
    location: "Calaca, Calabarzon, Philippines",
    date: "May 4 - 5",
    rating: "4.8 (230)",
    price: "95",
    time: "night",
    like: true,
  },
];
