export const categories = [
  {
    img: "/exploreImg1.png",
    name: "Townhouse",
  },
  {
    img: "/exploreImg2.png",
    name: "Apartment",
  },
  {
    img: "/exploreImg3.png",
    name: "Cabin",
  },
  {
    img: "/exploreImg4.png",
    name: "Tent",
  },
  {
    img: "/exploreImg5.png",
    name: "Condominium",
  },
  {
    img: "/exploreImg6.png",
    name: "Tiny House",
  },
  {
    img: "/exploreImg7.png",
    name: "Bungalow",
  },
  {
    img: "/exploreImg1.png",
    name: "Townhouse",
  },
  {
    img: "/exploreImg2.png",
    name: "Apartment",
  },
  {
    img: "/exploreImg3.png",
    name: "Cabin",
  },
  {
    img: "/exploreImg4.png",
    name: "Tent",
  },
  {
    img: "/exploreImg5.png",
    name: "Condominium",
  },
  {
    img: "/exploreImg6.png",
    name: "Tiny House",
  },
  {
    img: "/exploreImg7.png",
    name: "Bungalow",
  },
];

export const list = [
  {
    id: 1,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 2,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 3,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 4,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 5,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 6,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 7,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 8,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 9,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 10,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 11,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
  {
    id: 12,
    name: "Vintage Airstream Suite on Top of a Hill",
    location: "Calaca, Calabarzon, Philippines",
    rating: "4.8",
    reviews: "230",
    time: "night",
    price: "250",
    img: "https://picsum.photos/200",
  },
];
